name: Auto merge
on:
  pull_request:
permissions:
  contents: write
  checks: read
  pull-requests: write
jobs:
  auto-merge:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_merge.yml@f1ee54ff38b0eaaed9be6f5d184438c9b8a5b7eb # pinned to latest
    with:
      azure_cloud: true
      tfchecks_azure: '["tf-lint / tflint"]'
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
