name: Gitleaks PR Secret Scan

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    uses: clouddrove/github-shared-workflows/.github/workflows/gitleaks-pr-scan.yml@f1ee54ff38b0eaaed9be6f5d184438c9b8a5b7eb # pinned to latest
    secrets: inherit
