name: Module Test Harness

on:
  pull_request:

permissions:
  contents: read

jobs:
  basic-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@v2
    with:
      provider: digitalocean
      working_directory: ./_examples/basic/

  complete-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@v2
    with:
      provider: digitalocean
      working_directory: ./_examples/complete/

  soc2-baseline-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@v2
    with:
      provider: digitalocean
      working_directory: ./_examples/soc2-baseline/
