name: Module Test Harness

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@62909fc10e105bba5cba4ff73b03c020b97789d4
    with:
      provider: digitalocean
      working_directory: ./_examples/basic/
  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@62909fc10e105bba5cba4ff73b03c020b97789d4
    with:
      provider: digitalocean
      working_directory: ./_examples/complete/
