name: PR Validation

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr-checks.yml@7d78c7b4b3922e7577e222d4f48f1197c7d507c8 # pinned to latest
    secrets: inherit
    with:
      subjectPattern: '^.+$'
