name: PR Validation

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr-checks.yml@6f2dee689a9d21f44f1cbe66deb8f6777871ab8e # pinned to latest
    secrets: inherit
    with:
      subjectPattern: '^.+$'
