name: PR Validation

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr-checks.yml@7bc2965ff8f6b68db9402316dd5dd7498ec9c0e4 # pinned to latest
    secrets: inherit
    with:
      subjectPattern: '^.+$'
