name: Tag Release

on:
  pull_request:
    types: [closed]

jobs:
  handle-release:
    if: github.event.pull_request.merged == true && github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/release-tag.yml@v2
    with:
      target_branch: ${{ github.event.pull_request.base.ref }}
      tag_format: "vX.Y.Z"
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
