name: Tag Release

on:
  pull_request:
    types: [closed]

jobs:
  release:
    uses: clouddrove/github-shared-workflows/.github/workflows/tag-release.yml@6f2dee689a9d21f44f1cbe66deb8f6777871ab8e # pinned to latest
    with:
      target_branch: master
    secrets:
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
