name: Tag Release

on:
  pull_request:
    types: [closed]

jobs:
  release:
    uses: clouddrove/github-shared-workflows/.github/workflows/tag-release.yml@03dcb08c08de8e1798c735f548655e391f924277 # pinned to latest
    with:
      target_branch: master
    secrets:
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
